### ISSUE TITLE
Demo is broken (wrong Js-file)

### ISSUE THREAD

**Issue by christianselch** [mathiasbynens/jquery-noselect#1]
You try to load the plugin from "http://github.com/mathiasbynens/noSelect-jQuery-Plugin/raw/master/jquery.noselect.min.js", but the proper url is "https://raw.github.com/mathiasbynens/jquery-noselect/master/jquery.noselect.min.js".

**Comment by mathiasbynens** [comment]
Fixed, thanks!

http://mathiasbynens.be/demo/noselect
